[package]
name = "ioc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-rs = { workspace = true }
env_logger = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true, features = ["env-filter"] }
ioc_core = { workspace = true }
ioc_core_macro = { workspace = true }
ioc_mvc = { workspace = true, optional = true }
ioc_macro = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }

[features]
default = ["tracing_log", "mvc", "static-files"]
tracing_log = ["tracing-subscriber", "tracing"]
mvc = ["ioc_macro/mvc", "dep:ioc_mvc"]
static-files = ["ioc_mvc/static-files"]

[dev-dependencies]
anyhow = { workspace = true }
poem-openapi = { workspace = true }