[package]
name = "ioc_macro"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
proc-macro2 = { workspace = true, features = ["span-locations", "proc-macro", "nightly"] }
quote = { workspace = true }
syn = { workspace = true }
thiserror = { workspace = true }
darling = { workspace = true }
ioc_core_scan = { workspace = true }
ioc_mvc_scan = { workspace = true, optional = true }
log = { workspace = true }

[lib]
proc-macro = true

[features]
default = []
mvc = ["dep:ioc_mvc_scan"]


