[package]
name = "ioc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = { workspace = true }
ioc_core = { workspace = true }
ioc_derive = { workspace = true }
linkme = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }


[workspace]
members = ["ioc_core", "ioc_derive"]

[workspace.dependencies]
env_logger = "0.10.1"
anyhow = "1.0.79"
linkme = "0.3.18"
ioc_core = { path = "./ioc_core" }
ioc_derive = { path = "./ioc_derive" }
crossbeam-epoch = "0.9.16"
log = "0.4.20"
thiserror = "1.0.51"
proc-macro2 = "1.0.70"
quote = "1.0.33"
serde = { version = "1.0.193" }
syn = { version = "2.0.40", features = [
    "extra-traits",
    "derive",
    "parsing",
    "printing",
    "clone-impls",
    "proc-macro",
] }
toml = "0.8.8"
