[package]
name = "success"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.86"

[dependencies.ioc]
path = "../.."
features = ["tracing_log"]

[build-dependencies.ioc_scan]
path = "../../ioc_scan"

[dependencies.poem-openapi]
workspace = true