[package]
name = "ioc_core_scan"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
syn = { workspace = true, features = ["full", "fold", "visit"] }
thiserror = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
prettyplease = { workspace = true }